apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "chal"
spec:
  template:
    spec:
      containers:
      - name: "challenge"
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 45
          timeoutSeconds: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 30
      - name: "healthcheck"
        image: "healthcheck"
        command:
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.05"
        volumeMounts:
        - name: "healthcheck-secrets"
          mountPath: "/secrets"
          readOnly: true
        - name: "healthcheck-exploit-key"
          mountPath: "/keys"
          readOnly: true
        - name: "healthcheck-config"
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: "healthcheck-secrets"
        secret:
          secretName: "healthcheck-secrets"
          defaultMode: 0444
      - name: "healthcheck-exploit-key"
        secret:
          secretName: "healthcheck-exploit-key"
          defaultMode: 0444
      - name: "healthcheck-config"
        configMap:
          name: "healthcheck-config"
